S01_Django Setup/discussion/discussion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todolist/', include("todolist.urls")),
    path('admin/', admin.site.urls),
]

S01_Django Setup/discussion/todolist/urls.py
from django.urls import path

from . import views

# path() function 
# path(route, view, name)


app_name = 'todolist'
urlpatterns = [
	path('',views.index, name='index'),
	path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	# /todolist/register
	path('register', views.register, name="register"),
	path('change_password', views.change_password, name="change_password"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_task', views.add_task, name="add_task"),
	path('add_event', views.add_event, name="add_event"),
	path('event/<int:eventitem_id>/', views.eventitem, name='vieweventitem'),
	path('<int:todoitem_id>/edit', views.update_task, name="update_task" ),
	path('<int:todoitem_id>/delete', views.delete_task, name="delete_task" ),
	path('update_profile', views.update_profile, name="update_profile"),
]

S01_Django Setup/discussion/todolist/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import ForeignKey

# Create your models here.
class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="Pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class EventItem(models.Model):
	event_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="Pending")
	event_date = models.CharField(max_length=50)
	# date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

S01_Django Setup/discussion/todolist/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label="Password", max_length=20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)

class AddEventForm(forms.Form):
	event_name = forms.CharField(label="Event Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)
	event_date = forms.CharField(label="Event Date",max_length=50)
	

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label="Description", max_length=200)
	status = forms.CharField(label="status", max_length=50)

class RegisterForm(forms.Form):
	username = forms.CharField(label='User Name', max_length=50)
	first_name = forms.CharField(label='First Name', max_length=50)
	last_name = forms.CharField(label='Last Name', max_length=50)
	email = forms.CharField(label='Email', max_length=50)
	password = forms.CharField(label='Password', max_length=50)
	# confirm_password = forms.CharField(label="Confirm Password", max_length=50)

	# def clean_password_confirm(self):
	#         cleaned_data = super().clean()
	#         if cleaned_data.get('password') != cleaned_data.get('password_confirm'):
	#             raise ValidationError('Password fields do not match.')

class UpdateProfile(forms.Form):
	first_name = forms.CharField(label="First Name", max_length=50)
	last_name = forms.CharField(label="last_name", max_length=50)
	password = forms.CharField(label="Password", max_length=50)

S01_Django Setup/discussion/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
# "from" keyword allows importing of necessary classes, methods and other items needed in our application. 
# "import" keyword defines what we are importing from the package

# from django.http import HttpResponse
from .models import ToDoItem, EventItem
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm, AddEventForm, UpdateProfile

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password


# Create your views here.

def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	eventitem_list = EventItem.objects.filter(user_id=request.user.id)
	# output = ", ".join([todoitem.task_name for todoitem in todoitem_list])
	# template = loader.get_template("todolist/index.html")
	context = {
		'todoitem_list': todoitem_list,
		'eventitem_list': eventitem_list,
		'user': request.user
	}
	return render(request, "todolist/index.html", context) # HttpResponse(template.render(context, request))

def todoitem(request, todoitem_id):
	# response = "You are viewing the details of %s"
	# todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))
	# return render(request, "todolist/todoitem.html", todoitem)

	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

def eventitem(request, eventitem_id):
	eventitem = get_object_or_404(EventItem, pk=eventitem_id)
	return render(request, "todolist/eventitem.html", model_to_dict(eventitem))

# S03_Discussion

def register(request):
    is_user_registered = False
    context = {
        "is_user_registered": is_user_registered
    }

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid() == False:
            form = RegisterForm()

        else:
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']

            duplicates = User.objects.filter(username=username)
            if not duplicates:
                if is_user_registered == False:
                    User.objects.create(username=username, password=password, first_name=first_name, last_name=last_name, email=email)
                    return redirect('todolist:login')

            else:
                context = {
                    "error": True
                }   
    
    return render(request, "todolist/register.html", context)


def change_password(request):
	is_user_authenticated = False
	user = authenticate(username="johndoe", password="john1234")
	print(user)
	if user is not None:
		authenticated_user = User.objects.get(username='johndoe')
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		is_user_authenticated = True
		context = {
			"is_user_authenticated": is_user_authenticated
		}
	return render(request, "todolist/change_password.html", context)


def login_view(request):
	# username = "johndoe"
	# password = "johndoe1"
	# user = authenticate(username=username, password=password)
	# context = {
	# 	"is_user_authenticated": False
	# }
	# print(user)

	# if user is not None:
	# 	login(request, user)
	# 	return redirect("todolist:index")
	# else:

	context = {}
	if request.method == 'POST':
		form = LoginForm(request.POST)

		if form.is_valid() == False:
			form = LoginForm()

		else:
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			context = {
				"username": username, 
				"password": password
			}

			if user is not None:
				login(request, user)
				return redirect("todolist:index")
			else:
				context = {
				"error": True
				}

	return render(request, "todolist/login.html", context)
	# }

def logout_view(request):
	logout(request)
	return redirect("todolist:index")


def add_task(request):
	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()

		else: 
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			duplicates = ToDoItem.objects.filter(task_name=task_name)

			if not duplicates:
				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)
				return redirect ('todolist:index')

			else:
				context = {
					"error": True
				}

	return render(request, "todolist/add_task.html", context)

def add_event(request):
	context = {}

	if request.method == 'POST':
		form = AddEventForm(request.POST)

		if form.is_valid() == False:
			form = AddEventForm()

		else: 
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']
			event_date = form.cleaned_data['event_date']

			duplicates = EventItem.objects.filter(event_name=event_name)

			if not duplicates:
				EventItem.objects.create(event_name=event_name, description=description, event_date=event_date, user_id=request.user.id)
				return redirect ('todolist:index')

			else:
				context = {
					"error": True
				}

	return render(request, "todolist/add_event.html", context)



def update_task(request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status
	}

	if request.method == 'POST':
		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:
			form = UpdateTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:
				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()
				return redirect("todolist:index")
			else:
				context = {
					"error": True
				}

	return render(request, "todolist/update_task.html", context)



def delete_task(request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect("todolist:index")

def update_profile(request):

	    user = User.objects.filter()

	    context = {
	        "user": request.user,	        
	        "first_name": user[0].first_name,
	        "last_name": user[0].last_name,
	        "password": user[0].password
	        }

	    if request.method == 'POST':
	        form = UpdateProfile(request.POST)

	        if form.is_valid() == False:
	            form = UpdateProfile()
	        else:
	            first_name = form.cleaned_data['first_name']
	            last_name = form.cleaned_data['last_name']
	            password = form.cleaned_data['password']

	            if user:
	                user[0].first_name = first_name
	                user[0].last_name = last_name
	                user[0].password = password

	                user[0].save()
	                return redirect("todolist:index")
	            else:
	                context = {
	                    "error": True
	                }

	    return render(request, "todolist/update_profile.html", context)

S01_Django Setup/discussion/todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title%}Add Event{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Add An Event</h1>
					{% if error == True %}
						<p class="text-danger">Duplicate Event found</p>
					{% endif %}
					<form action="{% url 'todolist:add_event' %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
						    <label for="event_name">Event Name: </label>
						    <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
						</div>

						<div class="mb-3">
						    <label for="description">Description: </label>
						    <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
						</div>

						<div class="mb-3">
						    <label for="event_date">Event Date: </label>
						    <input class="form-control" id="event_date" type="date" name="event_date" value="{{ event_date }}" maxlength="50" required>
						</div>
						
						<div class="text-center">
					    	<input class="btn btn-success" type="submit" value="Add Event">
						</div>

					</form>
				</div>
			</div>
		</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center my-3">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}

S01_Django Setup/discussion/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title%}Add Task{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Add A Task</h1>
					{% if error == True %}
						<p class="text-danger">Duplicate task found</p>
					{% endif %}
					<form action="{% url 'todolist:add_task' %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
						    <label for="task_name">Task Name: </label>
						    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
						</div>

						<div class="mb-3">
						    <label for="description">Description: </label>
						    <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
						</div>

						<div class="text-center">
					    	<input class="btn btn-success" type="submit" value="Add Task">
						</div>

					</form>
				</div>
			</div>
		</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center my-3">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}

S01_Django Setup/discussion/todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password is correct</p>
{% else %}
	<h1>User password successfully updated</h1>
	<p>The password has been successfully updated</p>
{% endif %}

S01_Django Setup/discussion/todolist/templates/todolist/eventitem.html
{% extends 'base.html' %}

{% block title %}Your Current Events{% endblock %}

{% block content %}
	<div class="text-center my-3">
		<h1>Your Current Events</h1>
		<h1>{{ event_name }}</h1>
		<h3>Description</h3>
		<p>{{ description }}</p>
		<h3>Date</h3>
		<p>{{ event_date }}</p>	
		<h3>Status</h3>
		<p>{{ status }}</p>
		
		

		<button class="btn btn-warning mx-1 text-decoration-none">
			<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Home</a>
		</button>
		
	</div>
{% endblock %}

S01_Django Setup/discussion/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

    {% if todoitem_list and user.is_anonymous == False %}
        <h1 class="text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>
        
        <div class="container">
            <div class="row">
                <h3 class="text-center mb-3">My Task</h3>
                <ul class="list-group col-lg-2 offset-lg-5 text-center">
                    {% for todoitem in todoitem_list %}
                    <!-- <a href="/todolist/{{ todoitem.id }}/" class="text-decoration-none"> -->
                    <a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">
                        <li class="list-group-item">{{ todoitem.task_name }}</li>
                    </a>
                    {% endfor %}
                   
                </ul>
            </div>                      
        </div>
        <div class="container mt-3">
            <div class="row">
                <h3 class="text-center mb-3">My Events</h3>
                <ul class="list-group col-lg-2 offset-lg-5 text-center">
                    {% for eventitem in eventitem_list %}                    
                    <a href="{% url 'todolist:vieweventitem' eventitem.id %}" class="text-decoration-none">
                        <li class="list-group-item">{{ eventitem.event_name }}</li>
                    </a>
                    {% endfor %}
                </ul>
            </div>                        
        </div>
        <ul>
  
    {% elif user.is_anonymous == True %}
        <h1 class="text-center my-3">You are not authorized to access this page.</h1>
        <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
    {% else %}
        <p class="text-center">No task or events have been created</p>
    {% endif %}

{% endblock %}

S01_Django Setup/discussion/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title%}Login{% endblock %}

<!-- {% if is_user_authenticated == False %}
	<h1>Something went wrong</h1>
	<p>Please contact your administrator or reset your password</p>
	<a href="url 'todolist:index' ">Back to index page</a>
{% endif %} -->

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Login</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials, please check your username and password</p>
			{% endif %}
			<form action="{% url 'todolist:login' %}" method="post">
				<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
				<!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
				{% csrf_token %}

				<div class="mb-3">
				    <label for="username">Username: </label>
				    <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
				    <label for="password">Password: </label>
				    <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>

				<div class="text-center">
			    	<input class="btn btn-success" type="submit" value="Login">
				</div>

			</form>
		</div>
	</div>
</div>

{% endblock %}

S01_Django Setup/discussion/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
{% if is_user_registered == False %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <h1 class="text-center my-3">Register</h1>
                {% if password != password2 %}
                    <p class="text-danger">Password does not match.</p>
                {% endif %}
                <form action="{% url 'todolist:register' %}" method="post">
                    <!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
                    <!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="username">Username: </label>
                        <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
                    </div>

                    <div class="mb-3">
                        <label for="first_name">First Name: </label>
                        <input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="20" required>
                    </div>

                    <div class="mb-3">
                        <label for="last_name">Last Name: </label>
                        <input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="20" required>
                    </div>


                    <div class="mb-3">
                        <label for="email">Email: </label>
                        <input class="form-control" id="email" type="text" name="email" value="{{ email }}" maxlength="20" required>
                    </div>

                    <div class="mb-3">
                        <label for="password">Password: </label>
                        <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
                    </div>

                    <div class="mb-3">
                        <label for="password2">Verify Password: </label>
                        <input class="form-control" id="password2" type="password" name="password2" value="{{ password2 }}" maxlength="20" required>
                    </div>

                    <div class="text-center">
                        <input class="btn btn-success" type="submit" value="Register">
                    </div>

                </form>
            </div>
        </div>
    </div>
{% else %}
    <h1 class="text-center my-3">User Successfully Created!</h1>
    <p class="text-center my-3">The account for {{first_name}} {{last_name}} has been successfully created.</p>
{% endif %}

{% endblock %}

S01_Django Setup/discussion/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
	<div class="text-center my-3">
		<h1>{{ task_name }}</h1>
		<h3>Description</h3>
		<p>{{ description }}</p>
		<h3>Status</h3>
		<p>{{ status }}</p>
		
		<button class="btn btn-primary mx-1 text-decoration-none">
			<a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
		</button>

		<button class="btn btn-danger mx-1 text-decoration-none">
			<a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
		</button>

		<button class="btn btn-warning mx-1 text-decoration-none">
			<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Tasks</a>
		</button>
		
	</div>
{% endblock %}

<!-- <h1>{{ task_name }}</h1>
<h3>Description:</h3>
<p>{{ description }}</p>
<h3>Status</h3>
<p>{{ status }}</p>
<a href = "{% url 'todolist:index' %}">Back to index page</a> -->

S01_Django Setup/discussion/todolist/templates/todolist/update_profile.html
{% extends 'base.html' %}

{% block title %}Update Profile{% endblock %}

{% block content %}
    {% if user.is_anonymous == False %}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <h1 class="text-center my-3">Update Profile</h1>
                <form action="{% url 'todolist:update_profile' %}" method="post">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="username">Username: </label>
                        <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="50" disabled>
                    </div>

                    <div class="mb-3">
                        <label for="first_name">First Name: </label>
                        <input class="form-control" name="first_name" value="{{ first_name }}" required></input>
                    </div>
                    <div class="mb-3">
                        <label for="last_name">Last Name: </label>
                        <input class="form-control" name="last_name" value="{{ last_name }}" required></input>
                    </div>
                    <div class="mb-3">
                        <label for="password">Password: </label>
                        <input class="form-control" name="password" value="{{ password }}" required></input>
                    </div>
                    <div class="mb-3">
                        <label for="confirm_password">Confirm Password: </label>
                        <input class="form-control" name="confirm_password" value="{{ confirm_password }}" required></input>
                    </div>

                    <div class="text-center">
                        <input class="btn btn-success" type="submit" value="Update">
                    </div>

                </form>
            </div>
        </div>
    </div>
    {% else %}
        <h1>You are not authorized to access this page.</h1>
        <p>Kindly login <a href="{% url 'todolist:login'%}">here</a></p>
    {% endif %}
{% endblock %}

S01_Django Setup/discussion/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock%}

{% block content %}
	{% if user.is_anonymous == False %}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Update Task</h1>
					{% if error == True %}
						<p class="text-danger">Task not found</p>
					{% endif %}
					<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
						    <label for="task_name">Task Name: </label>
						    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
						</div>

						<div class="mb-3">
						    <label for="description">Description: </label>
						    <textarea class="form-control" name="description" required>{{ description }}</textarea>
						</div>

						<div class="mb-3">
						    <label for="status">Status: </label>
						    <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
						</div>

						<div class="text-center">
					    	<input class="btn btn-success" type="submit" value="Update Task">
						</div>

					</form>
				</div>
			</div>
		</div>
	{% else %}
		<h1>You are not authorized to access this page.</h1>
		<p>Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}