S01_Django Setup/discussion/discussion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todolist/', include("todolist.urls")),
    path('admin/', admin.site.urls),
]

S01_Django Setup/discussion/todolist/urls.py
from django.urls import path

from . import views

# path() function 
# path(route, view, name)


app_name = 'todolist'
urlpatterns = [
	path('',views.index, name='index'),
	path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	# /todolist/register
	path('register', views.register, name="register"),
	path('change_password', views.change_password, name="change_password"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_task', views.add_task, name="add_task"),
	path('add_event', views.add_event, name="add_event"),
	path('event/<int:eventitem_id>/', views.eventitem, name='vieweventitem'),
	path('<int:todoitem_id>/edit', views.update_task, name="update_task" ),
	path('<int:todoitem_id>/delete', views.delete_task, name="delete_task" ),
	path('update_profile', views.update_profile, name="update_profile"),
]

S01_Django Setup/discussion/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title%}To Do App{% endblock %}</title>

	<!-- Bootstrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
	<!-- <h1>Hello World!</h1> -->
	{% include 'navbar.html' %}
	{% block content %}
	{% endblock %}

	<!-- Bootstrap -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>
</html>

S01_Django Setup/discussion/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">To Do App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:add_task' %}">Add Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:add_event' %}">Add Event</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:update_profile' %}">Update Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>